name: Go actions
on:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      #/home/runner/work/actions
      - name: go path
        run: |
          ls
          cd ..
          pwd
          ls
          mkdir -vp go/{src/,bin/,pkg/}
          mv go-stress-testing go/src/
          export GOPATH=$(pwd)/go
          export GO111MODULE=off
          cd go/src/go-stress-testing
          pwd
          echo $(go env GOPATH)/bin/

#      - name: Go PATH
#        run: export PATH=$PATH:$(go env GOPATH)/bin/

      - name: ls
        run: |
          ls
          pwd

      - name: run
        run: go run main.go -c 1 -n 100 -u https://www.baidu.com/