name: Release
on:
  create:
    tags:
      - v*
jobs:

  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out chode
        uses: actions/checkout@v1

      - name: Validates GO releaser config
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: check

#/home/runner/work/actions/actions
      - name: go path
        run: |
          ls
          cd ..
          pwd
          mkdir -vp go/{src/,bin/,pkg/}
          mv go-stress-testing go/src/
          export GOPATH=${pwd}/go
          export GO111MODULE=off
          cd go/src/go-stress-testing

      - name: Go PATH
        run: export PATH=$PATH:$(go env GOPATH)/bin

      - name: Create release on GitHub
        uses: docker://goreleaser/goreleaser:latest
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}